-- =========================================================
-- 콩당콩당 - HTO(Hypertension Ontology) 적용
-- 출처: data/raw/ontology/Hypertension_Ontology.rdf
--
-- 다른 온톨로지와의 핵심 차이:
--   DOID/HP/CKDO/HTN/DMTO/CDPEO는 분류체계(is-a) 또는 위험도 산출 규칙인 반면,
--   HTO는 owl:Restriction(someValuesFrom)으로 표현된 진짜 관계 트리플을 가진다.
--   canCause(원인), createsTheRiskOf(위험), detects(검사로 발견), isSymptomOf(증상), treats(치료)
--   -> 고혈압의 원인-증상-검사-치료-합병증 그래프를 직접 탐색할 수 있다.
-- =========================================================

CREATE TABLE IF NOT EXISTS hto_concepts (
  concept_id   TEXT PRIMARY KEY,
  label_en     TEXT,
  label_ko     TEXT,
  parent_class TEXT
);

CREATE TABLE IF NOT EXISTS hto_relations (
  id            SERIAL PRIMARY KEY,
  from_concept  TEXT REFERENCES hto_concepts(concept_id),
  relation_type TEXT,   -- canCause | createsTheRiskOf | detects | isSymptomOf | treats
  to_concept    TEXT REFERENCES hto_concepts(concept_id)
);

INSERT INTO hto_concepts (concept_id, label_en, label_ko, parent_class) VALUES
('HTO:Anticonvulsant_Medications', 'Anticonvulsant Medications', '항경련제', 'HTO:Medication'),
('HTO:Arterial_Complications', 'Arterial Complications', '동맥 합병증', 'HTO:Cardiovascular_Complications'),
('HTO:Benign_Essential_Hypertension', 'Benign Essential Hypertension', '양성 본태성고혈압', 'HTO:Essential_Hypertension'),
('HTO:Benign_Hypertensive_Renal_Disease', 'Benign Hypertensive Renal Disease', '양성 고혈압성 신장질환', 'HTO:Renal_Hypertension'),
('HTO:Benign_Renovascular_Hypertension', 'Benign Renovascular Hypertension', '양성 신혈관성고혈압', 'HTO:Renal_Hypertension'),
('HTO:Benign_Secondary_Hypertension', 'Benign Secondary Hypertension', '양성 이차성고혈압', 'HTO:Secondary_Hypertension'),
('HTO:Blood_Pressure-related_Symptoms', 'Blood Pressure-related Symptoms', '혈압 관련 증상', 'HTO:Cardiovascular_Symptoms'),
('HTO:Blood_Vessel_Complications', 'Blood Vessel Complications', '혈관 합병증', 'HTO:Cardiovascular_Complications'),
('HTO:Cardiovascular_Assesment', 'Cardiovascular Assesment', '심혈관 평가', 'HTO:Hypertension_Detection'),
('HTO:Cardiovascular_Complications', 'Cardiovascular Complications', '심혈관 합병증', 'HTO:Hypertension_Complcations'),
('HTO:Cardiovascular_Conditions', 'Cardiovascular Conditions', '심혈관 상태', 'HTO:Other_Factors'),
('HTO:Cardiovascular_Symptoms', 'Cardiovascular Symptoms', '심혈관 증상', 'HTO:Hypertension_Symptoms'),
('HTO:Cardiovascular_support', 'Cardiovascular support', '심혈관 지지요법', 'HTO:Hospital-based_Treatments'),
('HTO:Cerebrovascular_Complications', 'Cerebrovascular Complications', '뇌혈관 합병증', 'HTO:Hypertension_Complcations'),
('HTO:Chest-related_Symptoms', 'Chest-related Symptoms', '가슴 관련 증상', 'HTO:Cardiovascular_Symptoms'),
('HTO:Circulation-related_Symptoms', 'Circulation-related Symptoms', '순환 관련 증상', 'HTO:Cardiovascular_Symptoms'),
('HTO:Circulatory_Symptoms', 'Circulatory Symptoms', '순환계 증상', 'HTO:Other_Symptoms'),
('HTO:Cognitive-and_Mental_Symptoms', 'Cognitive-and Mental Symptoms', '인지·정신 증상', 'HTO:Neurological_Symptoms'),
('HTO:Coronary_Artery-related_Complications', 'Coronary Artery-related Complications', '관상동맥 관련 합병증', 'HTO:Cardiovascular_Complications'),
('HTO:Corticosteriods_Medications', 'Corticosteriods Medications', '코르티코스테로이드제', 'HTO:Medication'),
('HTO:Diabetes', 'Diabetes', '당뇨병', 'HTO:Secondary_Hypertension'),
('HTO:Diabetes_Screening_and_Monitoring', 'Diabetes Screening and Monitoring', '당뇨병 선별·모니터링', 'HTO:Hypertension_Detection'),
('HTO:Diagnostic_Imaging', 'Diagnostic Imaging', '영상진단', 'HTO:Hypertension_Detection'),
('HTO:Diagnostic_Procedure', 'Diagnostic Procedure', '진단 시술', 'HTO:Renal_Assesment'),
('HTO:Eclampsia', 'Eclampsia', '자간증', 'HTO:Pre-Eclampsia'),
('HTO:Edema_and_Swelling', 'Edema and Swelling', '부종', 'HTO:Reanl_Symptoms'),
('HTO:Endocrine_Factors', 'Endocrine Factors', '내분비 요인', 'HTO:Medical_Conditions'),
('HTO:Enviromental_Pollution_Factors', 'Enviromental Pollution Factors', '환경오염 요인', 'HTO:Environmental_and_Occupational_Factors'),
('HTO:Environmental_and_Occupational_Factors', 'Environmental and Occupational Factors', '환경·직업 요인', 'HTO:Hypertension_Causes'),
('HTO:Essential_Hypertension', 'Essential Hypertension', '본태성고혈압', 'HTO:Hypertension_Types'),
('HTO:Exposure_to_Toxins', 'Exposure to Toxins', '독성물질 노출', 'HTO:Environmental_and_Occupational_Factors'),
('HTO:Eye_Examinations', 'Eye Examinations', '안과 검사', 'HTO:Hypertension_Detection'),
('HTO:Functional_Assesment', 'Functional Assesment', '기능 평가', 'HTO:Renal_Assesment'),
('HTO:Gastrointestinal_Symptoms', 'Gastrointestinal Symptoms', '위장관 증상', 'HTO:Other_Symptoms'),
('HTO:General_Medical_Care', 'General Medical Care', '일반 의료처치', 'HTO:Hospital-based_Treatments'),
('HTO:General_Symptoms', 'General Symptoms', '전신 증상', 'HTO:Neurological_Symptoms'),
('HTO:Genetic_and_Family_History', 'Genetic and Family History', '유전·가족력', 'HTO:Hypertension_Causes'),
('HTO:Heart-related_Symptoms', 'Heart-related Symptoms', '심장 관련 증상', 'HTO:Cardiovascular_Symptoms'),
('HTO:Hospital-based_Treatments', 'Hospital-based Treatments', '병원 치료', 'HTO:Hypertension_Treatment'),
('HTO:Hypertension_Causes', 'Hypertension Causes', '고혈압 원인', NULL),
('HTO:Hypertension_Complcations', 'Hypertension Complcations', '고혈압 합병증', NULL),
('HTO:Hypertension_Detection', 'Hypertension Detection', '고혈압 진단/검출', NULL),
('HTO:Hypertension_Medications', 'Hypertension Medications', '고혈압 약물', 'HTO:Medication'),
('HTO:Hypertension_Symptoms', 'Hypertension Symptoms', '고혈압 증상', NULL),
('HTO:Hypertension_Treatment', 'Hypertension Treatment', '고혈압 치료', NULL),
('HTO:Hypertension_Types', 'Hypertension Types', '고혈압 유형', NULL),
('HTO:Imaging', 'Imaging', '영상검사', 'HTO:Renal_Assesment'),
('HTO:Infectious_Disease', 'Infectious Disease', '감염질환', 'HTO:Environmental_and_Occupational_Factors'),
('HTO:Inflammatory_and_Autoimmune_Factors', 'Inflammatory and Autoimmune Factors', '염증·자가면역 요인', 'HTO:Medical_Conditions'),
('HTO:Insulin_Therapy', 'Insulin Therapy', '인슐린 치료', 'HTO:Medication'),
('HTO:Intravenous_Medications', 'Intravenous Medications', '정맥주사 약물', 'HTO:Medication'),
('HTO:Kidney_Damage', 'Kidney Damage', '신장 손상', 'HTO:Renal_Complicaion'),
('HTO:Kidney_Function', 'Kidney Function', '신장 기능', 'HTO:Reanl_Symptoms'),
('HTO:Kidney_Related_Factors', 'Kidney Related Factors', '신장 관련 요인', 'HTO:Medical_Conditions'),
('HTO:Laboratory_Test', 'Laboratory Test', '검사실 검사', 'HTO:Renal_Assesment'),
('HTO:Lifestyle_Factors', 'Lifestyle Factors', '생활습관 요인', 'HTO:Hypertension_Causes'),
('HTO:Lifestyle_Modifications', 'Lifestyle Modifications', '생활습관 교정', 'HTO:Hypertension_Treatment'),
('HTO:Liver_Related_Factors', 'Liver Related Factors', '간 관련 요인', 'HTO:Medical_Conditions'),
('HTO:Malignant_Essential_Hypertension', 'Malignant Essential Hypertension', '악성 본태성고혈압', 'HTO:Essential_Hypertension'),
('HTO:Malignant_Hypertensive_Renal_Disease', 'Malignant Hypertensive Renal Disease', '악성 고혈압성 신장질환', 'HTO:Renal_Hypertension'),
('HTO:Malignant_Renovascular_Hypertension', 'Malignant Renovascular Hypertension', '악성 신혈관성고혈압', 'HTO:Renal_Hypertension'),
('HTO:Malignant_Secondary_Hypertension', 'Malignant Secondary Hypertension', '악성 이차성고혈압', 'HTO:Secondary_Hypertension'),
('HTO:Medical_Conditions', 'Medical Conditions', '의학적 상태', 'HTO:Hypertension_Causes'),
('HTO:Medical_Treatments_Factors', 'Medical Treatments Factors', '의료처치 요인', 'HTO:Environmental_and_Occupational_Factors'),
('HTO:Medication', 'Medication', '약물(상위)', 'HTO:Hypertension_Treatment'),
('HTO:Medications', 'Medications', '약물', 'HTO:Other_Factors'),
('HTO:Metabolic_Changes', 'Metabolic Changes', '대사 변화', 'HTO:Reanl_Symptoms'),
('HTO:Metabolic_Factors', 'Metabolic Factors', '대사 요인', 'HTO:Medical_Conditions'),
('HTO:Mild_Pre-Eclampsia', 'Mild Pre-Eclampsia', '경증 전자간증', 'HTO:Pre-Eclampsia'),
('HTO:Monitoring_and_Follow-up', 'Monitoring and Follow-up', '모니터링·추적관찰', 'HTO:Hypertension_Treatment'),
('HTO:Mortality_and_Serious_Complications', 'Mortality and Serious Complications', '사망·중증합병증', 'HTO:Other_Complication'),
('HTO:Motor_Symptoms', 'Motor Symptoms', '운동 증상', 'HTO:Neurological_Symptoms'),
('HTO:Nephrosclerosis', 'Nephrosclerosis', '신장경화증', 'HTO:Renal_Hypertension'),
('HTO:Nephrotrophic_Syndrome', 'Nephrotrophic Syndrome', '신증후군성 증후군', 'HTO:Renal_Complicaion'),
('HTO:Neurological_Factors', 'Neurological Factors', '신경학적 요인', 'HTO:Medical_Conditions'),
('HTO:Neurological_Symptoms', 'Neurological Symptoms', '신경학적 증상', 'HTO:Hypertension_Symptoms'),
('HTO:Neuropathic_Complications', 'Neuropathic Complications', '신경병증성 합병증', 'HTO:Ophthalmic_Complications'),
('HTO:Obstetric_Care', 'Obstetric Care', '산과 케어', 'HTO:Hospital-based_Treatments'),
('HTO:Occupational_Factors', 'Occupational Factors', '직업적 요인', 'HTO:Environmental_and_Occupational_Factors'),
('HTO:Ophthalmic_Complications', 'Ophthalmic Complications', '안과 합병증', 'HTO:Hypertension_Complcations'),
('HTO:Organ-specific_Complications', 'Organ-specific Complications', '장기특이적 합병증', 'HTO:Cardiovascular_Complications'),
('HTO:Other_Complication', 'Other Complication', '기타 합병증(단수)', 'HTO:Hypertension_Complcations'),
('HTO:Other_Complications', 'Other Complications', '기타 합병증', 'HTO:Cardiovascular_Complications'),
('HTO:Other_Factors', 'Other Factors', '기타 요인', 'HTO:Hypertension_Causes'),
('HTO:Other_Symptoms', 'Other Symptoms', '기타 증상', 'HTO:Hypertension_Symptoms'),
('HTO:Pancreatic_Factors', 'Pancreatic Factors', '췌장 요인', 'HTO:Other_Factors'),
('HTO:Perinatal_Factors', 'Perinatal Factors', '주산기 요인', 'HTO:Environmental_and_Occupational_Factors'),
('HTO:Persistent_Fetal_Circulation_Syndrome', 'Persistent Fetal Circulation Syndrome', '지속성 태아순환증후군', 'HTO:Pulmonary_Hypertension'),
('HTO:Pre-Eclampsia', 'Pre-Eclampsia', '전자간증', 'HTO:Hypertension_Types'),
('HTO:Pregnancy_Related_Factors', 'Pregnancy Related Factors', '임신 관련 요인', 'HTO:Medical_Conditions'),
('HTO:Pregnancy_and_Birth-related-complications', 'Pregnancy and Birth-related-complications', '임신·출산 관련 합병증', 'HTO:Other_Complication'),
('HTO:Proteinuria', 'Proteinuria', '단백뇨', 'HTO:Renal_Complicaion'),
('HTO:Pulmonary_Complications', 'Pulmonary Complications', '폐 합병증', 'HTO:Renal_Complicaion'),
('HTO:Pulmonary_Hypertension', 'Pulmonary Hypertension', '폐고혈압', 'HTO:Hypertension_Types'),
('HTO:Pulmonary_Venoocclusive_Disease', 'Pulmonary Venoocclusive Disease', '폐정맥폐쇄병', 'HTO:Pulmonary_Hypertension'),
('HTO:Reanl_Symptoms', 'Reanl Symptoms', '신장 증상', 'HTO:Hypertension_Symptoms'),
('HTO:Renal_Assesment', 'Renal Assesment', '신장 평가', 'HTO:Hypertension_Detection'),
('HTO:Renal_Care', 'Renal Care', '신장 관리', 'HTO:Hospital-based_Treatments'),
('HTO:Renal_Complicaion', 'Renal Complicaion', '신장 합병증', 'HTO:Hypertension_Complcations'),
('HTO:Renal_Failure', 'Renal Failure', '신부전', 'HTO:Renal_Complicaion')
ON CONFLICT (concept_id) DO NOTHING;

INSERT INTO hto_concepts (concept_id, label_en, label_ko, parent_class) VALUES
('HTO:Renal_Hypertension', 'Renal Hypertension', '신성고혈압', 'HTO:Secondary_Hypertension'),
('HTO:Renal_Related_Factors', 'Renal Related Factors', '신장 관련 요인', 'HTO:Medical_Conditions'),
('HTO:Renovascular_Hypertension', 'Renovascular Hypertension', '신혈관성고혈압', 'HTO:Renal_Hypertension'),
('HTO:Respiratory_Factors', 'Respiratory Factors', '호흡기 요인', 'HTO:Medical_Conditions'),
('HTO:Respiratory_Support', 'Respiratory Support', '호흡 지지요법', 'HTO:Hospital-based_Treatments'),
('HTO:Respiratory_Symptoms', 'Respiratory Symptoms', '호흡기 증상', 'HTO:Cardiovascular_Symptoms'),
('HTO:Retinal_Complications', 'Retinal Complications', '망막 합병증', 'HTO:Ophthalmic_Complications'),
('HTO:Secondary_Hypertension', 'Secondary Hypertension', '이차성고혈압', 'HTO:Hypertension_Types'),
('HTO:Sensory_Symptoms', 'Sensory Symptoms', '감각 증상', 'HTO:Neurological_Symptoms'),
('HTO:Severe_Pre-Eclampsia', 'Severe Pre-Eclampsia', '중증 전자간증', 'HTO:Pre-Eclampsia'),
('HTO:Surgical_Interventions', 'Surgical Interventions', '수술적 치료', 'HTO:Hospital-based_Treatments'),
('HTO:Urinary_Changes', 'Urinary Changes', '소변 변화', 'HTO:Reanl_Symptoms'),
('HTO:Vascular_Factors', 'Vascular Factors', '혈관 요인', 'HTO:Medical_Conditions'),
('HTO:Visual_Symptoms', 'Visual Symptoms', '시각 증상', 'HTO:Neurological_Symptoms')
ON CONFLICT (concept_id) DO NOTHING;

INSERT INTO hto_relations (from_concept, relation_type, to_concept) VALUES
('HTO:Anticonvulsant_Medications', 'treats', 'HTO:Eclampsia'),
('HTO:Arterial_Complications', 'createsTheRiskOf', 'HTO:Benign_Secondary_Hypertension'),
('HTO:Arterial_Complications', 'createsTheRiskOf', 'HTO:Malignant_Essential_Hypertension'),
('HTO:Blood_Pressure-related_Symptoms', 'isSymptomOf', 'HTO:Benign_Hypertensive_Renal_Disease'),
('HTO:Blood_Pressure-related_Symptoms', 'isSymptomOf', 'HTO:Benign_Renovascular_Hypertension'),
('HTO:Blood_Pressure-related_Symptoms', 'isSymptomOf', 'HTO:Eclampsia'),
('HTO:Blood_Pressure-related_Symptoms', 'isSymptomOf', 'HTO:Malignant_Secondary_Hypertension'),
('HTO:Blood_Pressure-related_Symptoms', 'isSymptomOf', 'HTO:Mild_Pre-Eclampsia'),
('HTO:Blood_Pressure-related_Symptoms', 'isSymptomOf', 'HTO:Nephrosclerosis'),
('HTO:Blood_Pressure-related_Symptoms', 'isSymptomOf', 'HTO:Persistent_Fetal_Circulation_Syndrome'),
('HTO:Blood_Pressure-related_Symptoms', 'isSymptomOf', 'HTO:Renovascular_Hypertension'),
('HTO:Blood_Pressure-related_Symptoms', 'isSymptomOf', 'HTO:Severe_Pre-Eclampsia'),
('HTO:Blood_Vessel_Complications', 'createsTheRiskOf', 'HTO:Malignant_Essential_Hypertension'),
('HTO:Cardiovascular_Assesment', 'detects', 'HTO:Benign_Essential_Hypertension'),
('HTO:Cardiovascular_Assesment', 'detects', 'HTO:Benign_Renovascular_Hypertension'),
('HTO:Cardiovascular_Assesment', 'detects', 'HTO:Benign_Secondary_Hypertension'),
('HTO:Cardiovascular_Assesment', 'detects', 'HTO:Eclampsia'),
('HTO:Cardiovascular_Assesment', 'detects', 'HTO:Malignant_Essential_Hypertension'),
('HTO:Cardiovascular_Assesment', 'detects', 'HTO:Malignant_Hypertensive_Renal_Disease'),
('HTO:Cardiovascular_Assesment', 'detects', 'HTO:Malignant_Renovascular_Hypertension'),
('HTO:Cardiovascular_Assesment', 'detects', 'HTO:Malignant_Secondary_Hypertension'),
('HTO:Cardiovascular_Assesment', 'detects', 'HTO:Mild_Pre-Eclampsia'),
('HTO:Cardiovascular_Assesment', 'detects', 'HTO:Nephrosclerosis'),
('HTO:Cardiovascular_Assesment', 'detects', 'HTO:Persistent_Fetal_Circulation_Syndrome'),
('HTO:Cardiovascular_Assesment', 'detects', 'HTO:Pulmonary_Venoocclusive_Disease'),
('HTO:Cardiovascular_Assesment', 'detects', 'HTO:Severe_Pre-Eclampsia'),
('HTO:Cardiovascular_Complications', 'createsTheRiskOf', 'HTO:Benign_Renovascular_Hypertension'),
('HTO:Cardiovascular_Complications', 'createsTheRiskOf', 'HTO:Diabetes'),
('HTO:Cardiovascular_Complications', 'createsTheRiskOf', 'HTO:Malignant_Renovascular_Hypertension'),
('HTO:Cardiovascular_Conditions', 'canCause', 'HTO:Benign_Renovascular_Hypertension'),
('HTO:Cardiovascular_Conditions', 'canCause', 'HTO:Diabetes'),
('HTO:Cardiovascular_Conditions', 'canCause', 'HTO:Malignant_Renovascular_Hypertension'),
('HTO:Cardiovascular_Conditions', 'canCause', 'HTO:Malignant_Secondary_Hypertension'),
('HTO:Cardiovascular_Conditions', 'canCause', 'HTO:Nephrosclerosis'),
('HTO:Cardiovascular_Conditions', 'canCause', 'HTO:Renovascular_Hypertension'),
('HTO:Cardiovascular_support', 'treats', 'HTO:Malignant_Renovascular_Hypertension'),
('HTO:Cardiovascular_support', 'treats', 'HTO:Nephrosclerosis'),
('HTO:Cardiovascular_support', 'treats', 'HTO:Renovascular_Hypertension'),
('HTO:Cerebrovascular_Complications', 'createsTheRiskOf', 'HTO:Benign_Essential_Hypertension'),
('HTO:Cerebrovascular_Complications', 'createsTheRiskOf', 'HTO:Benign_Hypertensive_Renal_Disease'),
('HTO:Cerebrovascular_Complications', 'createsTheRiskOf', 'HTO:Benign_Renovascular_Hypertension'),
('HTO:Cerebrovascular_Complications', 'createsTheRiskOf', 'HTO:Benign_Secondary_Hypertension'),
('HTO:Cerebrovascular_Complications', 'createsTheRiskOf', 'HTO:Eclampsia'),
('HTO:Cerebrovascular_Complications', 'createsTheRiskOf', 'HTO:Malignant_Essential_Hypertension'),
('HTO:Cerebrovascular_Complications', 'createsTheRiskOf', 'HTO:Malignant_Hypertensive_Renal_Disease'),
('HTO:Cerebrovascular_Complications', 'createsTheRiskOf', 'HTO:Malignant_Renovascular_Hypertension'),
('HTO:Cerebrovascular_Complications', 'createsTheRiskOf', 'HTO:Malignant_Secondary_Hypertension'),
('HTO:Cerebrovascular_Complications', 'createsTheRiskOf', 'HTO:Persistent_Fetal_Circulation_Syndrome'),
('HTO:Cerebrovascular_Complications', 'createsTheRiskOf', 'HTO:Renovascular_Hypertension'),
('HTO:Cerebrovascular_Complications', 'createsTheRiskOf', 'HTO:Severe_Pre-Eclampsia'),
('HTO:Chest-related_Symptoms', 'isSymptomOf', 'HTO:Benign_Renovascular_Hypertension'),
('HTO:Chest-related_Symptoms', 'isSymptomOf', 'HTO:Malignant_Essential_Hypertension'),
('HTO:Chest-related_Symptoms', 'isSymptomOf', 'HTO:Malignant_Hypertensive_Renal_Disease'),
('HTO:Chest-related_Symptoms', 'isSymptomOf', 'HTO:Malignant_Renovascular_Hypertension'),
('HTO:Chest-related_Symptoms', 'isSymptomOf', 'HTO:Malignant_Secondary_Hypertension'),
('HTO:Chest-related_Symptoms', 'isSymptomOf', 'HTO:Pulmonary_Venoocclusive_Disease'),
('HTO:Circulation-related_Symptoms', 'isSymptomOf', 'HTO:Persistent_Fetal_Circulation_Syndrome'),
('HTO:Circulation-related_Symptoms', 'isSymptomOf', 'HTO:Renovascular_Hypertension'),
('HTO:Circulatory_Symptoms', 'isSymptomOf', 'HTO:Benign_Essential_Hypertension'),
('HTO:Circulatory_Symptoms', 'isSymptomOf', 'HTO:Diabetes'),
('HTO:Circulatory_Symptoms', 'isSymptomOf', 'HTO:Eclampsia'),
('HTO:Circulatory_Symptoms', 'isSymptomOf', 'HTO:Nephrosclerosis'),
('HTO:Cognitive-and_Mental_Symptoms', 'isSymptomOf', 'HTO:Benign_Essential_Hypertension'),
('HTO:Cognitive-and_Mental_Symptoms', 'isSymptomOf', 'HTO:Benign_Hypertensive_Renal_Disease'),
('HTO:Cognitive-and_Mental_Symptoms', 'isSymptomOf', 'HTO:Benign_Renovascular_Hypertension'),
('HTO:Cognitive-and_Mental_Symptoms', 'isSymptomOf', 'HTO:Benign_Secondary_Hypertension'),
('HTO:Cognitive-and_Mental_Symptoms', 'isSymptomOf', 'HTO:Diabetes'),
('HTO:Cognitive-and_Mental_Symptoms', 'isSymptomOf', 'HTO:Eclampsia'),
('HTO:Cognitive-and_Mental_Symptoms', 'isSymptomOf', 'HTO:Malignant_Essential_Hypertension'),
('HTO:Cognitive-and_Mental_Symptoms', 'isSymptomOf', 'HTO:Malignant_Hypertensive_Renal_Disease'),
('HTO:Cognitive-and_Mental_Symptoms', 'isSymptomOf', 'HTO:Malignant_Renovascular_Hypertension'),
('HTO:Cognitive-and_Mental_Symptoms', 'isSymptomOf', 'HTO:Malignant_Secondary_Hypertension'),
('HTO:Cognitive-and_Mental_Symptoms', 'isSymptomOf', 'HTO:Mild_Pre-Eclampsia'),
('HTO:Cognitive-and_Mental_Symptoms', 'isSymptomOf', 'HTO:Nephrosclerosis'),
('HTO:Cognitive-and_Mental_Symptoms', 'isSymptomOf', 'HTO:Pulmonary_Venoocclusive_Disease'),
('HTO:Cognitive-and_Mental_Symptoms', 'isSymptomOf', 'HTO:Renovascular_Hypertension'),
('HTO:Cognitive-and_Mental_Symptoms', 'isSymptomOf', 'HTO:Severe_Pre-Eclampsia'),
('HTO:Coronary_Artery-related_Complications', 'createsTheRiskOf', 'HTO:Benign_Renovascular_Hypertension'),
('HTO:Coronary_Artery-related_Complications', 'createsTheRiskOf', 'HTO:Benign_Secondary_Hypertension'),
('HTO:Coronary_Artery-related_Complications', 'createsTheRiskOf', 'HTO:Eclampsia'),
('HTO:Coronary_Artery-related_Complications', 'createsTheRiskOf', 'HTO:Malignant_Essential_Hypertension'),
('HTO:Coronary_Artery-related_Complications', 'createsTheRiskOf', 'HTO:Malignant_Hypertensive_Renal_Disease'),
('HTO:Coronary_Artery-related_Complications', 'createsTheRiskOf', 'HTO:Malignant_Renovascular_Hypertension'),
('HTO:Coronary_Artery-related_Complications', 'createsTheRiskOf', 'HTO:Malignant_Secondary_Hypertension'),
('HTO:Coronary_Artery-related_Complications', 'createsTheRiskOf', 'HTO:Persistent_Fetal_Circulation_Syndrome'),
('HTO:Coronary_Artery-related_Complications', 'createsTheRiskOf', 'HTO:Pulmonary_Venoocclusive_Disease'),
('HTO:Coronary_Artery-related_Complications', 'createsTheRiskOf', 'HTO:Renovascular_Hypertension'),
('HTO:Corticosteriods_Medications', 'treats', 'HTO:Mild_Pre-Eclampsia'),
('HTO:Corticosteriods_Medications', 'treats', 'HTO:Severe_Pre-Eclampsia'),
('HTO:Diabetes_Screening_and_Monitoring', 'detects', 'HTO:Diabetes'),
('HTO:Diagnostic_Imaging', 'detects', 'HTO:Benign_Hypertensive_Renal_Disease'),
('HTO:Diagnostic_Imaging', 'detects', 'HTO:Benign_Secondary_Hypertension'),
('HTO:Diagnostic_Imaging', 'detects', 'HTO:Eclampsia'),
('HTO:Diagnostic_Imaging', 'detects', 'HTO:Malignant_Essential_Hypertension'),
('HTO:Diagnostic_Imaging', 'detects', 'HTO:Malignant_Hypertensive_Renal_Disease'),
('HTO:Diagnostic_Imaging', 'detects', 'HTO:Malignant_Renovascular_Hypertension'),
('HTO:Diagnostic_Imaging', 'detects', 'HTO:Malignant_Secondary_Hypertension'),
('HTO:Diagnostic_Imaging', 'detects', 'HTO:Nephrosclerosis'),
('HTO:Diagnostic_Imaging', 'detects', 'HTO:Pulmonary_Venoocclusive_Disease'),
('HTO:Diagnostic_Imaging', 'detects', 'HTO:Renovascular_Hypertension');

INSERT INTO hto_relations (from_concept, relation_type, to_concept) VALUES
('HTO:Diagnostic_Imaging', 'detects', 'HTO:Severe_Pre-Eclampsia'),
('HTO:Diagnostic_Procedure', 'detects', 'HTO:Nephrosclerosis'),
('HTO:Edema_and_Swelling', 'isSymptomOf', 'HTO:Benign_Hypertensive_Renal_Disease'),
('HTO:Edema_and_Swelling', 'isSymptomOf', 'HTO:Diabetes'),
('HTO:Edema_and_Swelling', 'isSymptomOf', 'HTO:Eclampsia'),
('HTO:Edema_and_Swelling', 'isSymptomOf', 'HTO:Malignant_Hypertensive_Renal_Disease'),
('HTO:Edema_and_Swelling', 'isSymptomOf', 'HTO:Malignant_Secondary_Hypertension'),
('HTO:Edema_and_Swelling', 'isSymptomOf', 'HTO:Mild_Pre-Eclampsia'),
('HTO:Edema_and_Swelling', 'isSymptomOf', 'HTO:Nephrosclerosis'),
('HTO:Edema_and_Swelling', 'isSymptomOf', 'HTO:Severe_Pre-Eclampsia'),
('HTO:Endocrine_Factors', 'canCause', 'HTO:Benign_Secondary_Hypertension'),
('HTO:Environmental_and_Occupational_Factors', 'canCause', 'HTO:Severe_Pre-Eclampsia'),
('HTO:Exposure_to_Toxins', 'canCause', 'HTO:Diabetes'),
('HTO:Eye_Examinations', 'detects', 'HTO:Malignant_Essential_Hypertension'),
('HTO:Functional_Assesment', 'detects', 'HTO:Malignant_Hypertensive_Renal_Disease'),
('HTO:Functional_Assesment', 'detects', 'HTO:Renovascular_Hypertension'),
('HTO:Gastrointestinal_Symptoms', 'isSymptomOf', 'HTO:Eclampsia'),
('HTO:Gastrointestinal_Symptoms', 'isSymptomOf', 'HTO:Malignant_Essential_Hypertension'),
('HTO:Gastrointestinal_Symptoms', 'isSymptomOf', 'HTO:Malignant_Hypertensive_Renal_Disease'),
('HTO:Gastrointestinal_Symptoms', 'isSymptomOf', 'HTO:Malignant_Secondary_Hypertension'),
('HTO:Gastrointestinal_Symptoms', 'isSymptomOf', 'HTO:Mild_Pre-Eclampsia'),
('HTO:Gastrointestinal_Symptoms', 'isSymptomOf', 'HTO:Nephrosclerosis'),
('HTO:Gastrointestinal_Symptoms', 'isSymptomOf', 'HTO:Persistent_Fetal_Circulation_Syndrome'),
('HTO:Gastrointestinal_Symptoms', 'isSymptomOf', 'HTO:Severe_Pre-Eclampsia'),
('HTO:General_Medical_Care', 'treats', 'HTO:Eclampsia'),
('HTO:General_Medical_Care', 'treats', 'HTO:Malignant_Essential_Hypertension'),
('HTO:General_Medical_Care', 'treats', 'HTO:Mild_Pre-Eclampsia'),
('HTO:General_Medical_Care', 'treats', 'HTO:Persistent_Fetal_Circulation_Syndrome'),
('HTO:General_Medical_Care', 'treats', 'HTO:Pulmonary_Venoocclusive_Disease'),
('HTO:General_Symptoms', 'isSymptomOf', 'HTO:Persistent_Fetal_Circulation_Syndrome'),
('HTO:Genetic_and_Family_History', 'canCause', 'HTO:Benign_Essential_Hypertension'),
('HTO:Genetic_and_Family_History', 'canCause', 'HTO:Diabetes'),
('HTO:Genetic_and_Family_History', 'canCause', 'HTO:Eclampsia'),
('HTO:Genetic_and_Family_History', 'canCause', 'HTO:Malignant_Essential_Hypertension'),
('HTO:Genetic_and_Family_History', 'canCause', 'HTO:Persistent_Fetal_Circulation_Syndrome'),
('HTO:Genetic_and_Family_History', 'canCause', 'HTO:Pulmonary_Venoocclusive_Disease'),
('HTO:Genetic_and_Family_History', 'canCause', 'HTO:Severe_Pre-Eclampsia'),
('HTO:Heart-related_Symptoms', 'isSymptomOf', 'HTO:Persistent_Fetal_Circulation_Syndrome'),
('HTO:Heart-related_Symptoms', 'isSymptomOf', 'HTO:Renovascular_Hypertension'),
('HTO:Hypertension_Medications', 'treats', 'HTO:Benign_Essential_Hypertension'),
('HTO:Hypertension_Medications', 'treats', 'HTO:Benign_Hypertensive_Renal_Disease'),
('HTO:Hypertension_Medications', 'treats', 'HTO:Benign_Renovascular_Hypertension'),
('HTO:Hypertension_Medications', 'treats', 'HTO:Diabetes'),
('HTO:Hypertension_Medications', 'treats', 'HTO:Eclampsia'),
('HTO:Hypertension_Medications', 'treats', 'HTO:Malignant_Essential_Hypertension'),
('HTO:Hypertension_Medications', 'treats', 'HTO:Malignant_Hypertensive_Renal_Disease'),
('HTO:Hypertension_Medications', 'treats', 'HTO:Malignant_Renovascular_Hypertension'),
('HTO:Hypertension_Medications', 'treats', 'HTO:Malignant_Secondary_Hypertension'),
('HTO:Hypertension_Medications', 'treats', 'HTO:Mild_Pre-Eclampsia'),
('HTO:Hypertension_Medications', 'treats', 'HTO:Nephrosclerosis'),
('HTO:Hypertension_Medications', 'treats', 'HTO:Pulmonary_Venoocclusive_Disease'),
('HTO:Hypertension_Medications', 'treats', 'HTO:Renovascular_Hypertension'),
('HTO:Hypertension_Medications', 'treats', 'HTO:Severe_Pre-Eclampsia'),
('HTO:Imaging', 'detects', 'HTO:Benign_Hypertensive_Renal_Disease'),
('HTO:Imaging', 'detects', 'HTO:Benign_Renovascular_Hypertension'),
('HTO:Imaging', 'detects', 'HTO:Malignant_Hypertensive_Renal_Disease'),
('HTO:Imaging', 'detects', 'HTO:Malignant_Renovascular_Hypertension'),
('HTO:Imaging', 'detects', 'HTO:Malignant_Secondary_Hypertension'),
('HTO:Imaging', 'detects', 'HTO:Nephrosclerosis'),
('HTO:Imaging', 'detects', 'HTO:Renovascular_Hypertension'),
('HTO:Infectious_Disease', 'canCause', 'HTO:Pulmonary_Venoocclusive_Disease'),
('HTO:Inflammatory_and_Autoimmune_Factors', 'canCause', 'HTO:Benign_Secondary_Hypertension'),
('HTO:Inflammatory_and_Autoimmune_Factors', 'canCause', 'HTO:Diabetes'),
('HTO:Inflammatory_and_Autoimmune_Factors', 'canCause', 'HTO:Mild_Pre-Eclampsia'),
('HTO:Insulin_Therapy', 'treats', 'HTO:Diabetes'),
('HTO:Intravenous_Medications', 'treats', 'HTO:Malignant_Essential_Hypertension'),
('HTO:Kidney_Damage', 'createsTheRiskOf', 'HTO:Benign_Essential_Hypertension'),
('HTO:Kidney_Damage', 'createsTheRiskOf', 'HTO:Benign_Hypertensive_Renal_Disease'),
('HTO:Kidney_Damage', 'createsTheRiskOf', 'HTO:Benign_Renovascular_Hypertension'),
('HTO:Kidney_Damage', 'createsTheRiskOf', 'HTO:Benign_Secondary_Hypertension'),
('HTO:Kidney_Damage', 'createsTheRiskOf', 'HTO:Eclampsia'),
('HTO:Kidney_Damage', 'createsTheRiskOf', 'HTO:Malignant_Essential_Hypertension'),
('HTO:Kidney_Damage', 'createsTheRiskOf', 'HTO:Malignant_Renovascular_Hypertension'),
('HTO:Kidney_Damage', 'createsTheRiskOf', 'HTO:Nephrosclerosis'),
('HTO:Kidney_Damage', 'createsTheRiskOf', 'HTO:Severe_Pre-Eclampsia'),
('HTO:Kidney_Function', 'isSymptomOf', 'HTO:Benign_Hypertensive_Renal_Disease'),
('HTO:Kidney_Function', 'isSymptomOf', 'HTO:Benign_Renovascular_Hypertension'),
('HTO:Kidney_Function', 'isSymptomOf', 'HTO:Renovascular_Hypertension'),
('HTO:Kidney_Related_Factors', 'canCause', 'HTO:Malignant_Essential_Hypertension'),
('HTO:Kidney_Related_Factors', 'canCause', 'HTO:Malignant_Hypertensive_Renal_Disease'),
('HTO:Laboratory_Test', 'detects', 'HTO:Benign_Renovascular_Hypertension'),
('HTO:Laboratory_Test', 'detects', 'HTO:Malignant_Hypertensive_Renal_Disease'),
('HTO:Laboratory_Test', 'detects', 'HTO:Renovascular_Hypertension'),
('HTO:Lifestyle_Factors', 'canCause', 'HTO:Benign_Essential_Hypertension'),
('HTO:Lifestyle_Factors', 'canCause', 'HTO:Benign_Hypertensive_Renal_Disease'),
('HTO:Lifestyle_Factors', 'canCause', 'HTO:Diabetes'),
('HTO:Lifestyle_Factors', 'canCause', 'HTO:Malignant_Essential_Hypertension'),
('HTO:Lifestyle_Factors', 'canCause', 'HTO:Mild_Pre-Eclampsia'),
('HTO:Lifestyle_Factors', 'canCause', 'HTO:Nephrosclerosis'),
('HTO:Lifestyle_Factors', 'canCause', 'HTO:Persistent_Fetal_Circulation_Syndrome'),
('HTO:Lifestyle_Modifications', 'treats', 'HTO:Benign_Essential_Hypertension'),
('HTO:Lifestyle_Modifications', 'treats', 'HTO:Benign_Hypertensive_Renal_Disease'),
('HTO:Lifestyle_Modifications', 'treats', 'HTO:Benign_Renovascular_Hypertension'),
('HTO:Lifestyle_Modifications', 'treats', 'HTO:Benign_Secondary_Hypertension'),
('HTO:Lifestyle_Modifications', 'treats', 'HTO:Diabetes'),
('HTO:Lifestyle_Modifications', 'treats', 'HTO:Malignant_Essential_Hypertension'),
('HTO:Lifestyle_Modifications', 'treats', 'HTO:Malignant_Hypertensive_Renal_Disease'),
('HTO:Lifestyle_Modifications', 'treats', 'HTO:Mild_Pre-Eclampsia'),
('HTO:Lifestyle_Modifications', 'treats', 'HTO:Nephrosclerosis'),
('HTO:Lifestyle_Modifications', 'treats', 'HTO:Renovascular_Hypertension');

INSERT INTO hto_relations (from_concept, relation_type, to_concept) VALUES
('HTO:Liver_Related_Factors', 'canCause', 'HTO:Eclampsia'),
('HTO:Medical_Treatments_Factors', 'canCause', 'HTO:Pulmonary_Venoocclusive_Disease'),
('HTO:Medications', 'canCause', 'HTO:Benign_Secondary_Hypertension'),
('HTO:Medications', 'canCause', 'HTO:Malignant_Hypertensive_Renal_Disease'),
('HTO:Metabolic_Changes', 'isSymptomOf', 'HTO:Diabetes'),
('HTO:Metabolic_Factors', 'canCause', 'HTO:Benign_Hypertensive_Renal_Disease'),
('HTO:Metabolic_Factors', 'canCause', 'HTO:Diabetes'),
('HTO:Metabolic_Factors', 'canCause', 'HTO:Mild_Pre-Eclampsia'),
('HTO:Metabolic_Factors', 'canCause', 'HTO:Nephrosclerosis'),
('HTO:Metabolic_Factors', 'canCause', 'HTO:Severe_Pre-Eclampsia'),
('HTO:Monitoring_and_Follow-up', 'treats', 'HTO:Benign_Secondary_Hypertension'),
('HTO:Monitoring_and_Follow-up', 'treats', 'HTO:Diabetes'),
('HTO:Monitoring_and_Follow-up', 'treats', 'HTO:Eclampsia'),
('HTO:Monitoring_and_Follow-up', 'treats', 'HTO:Malignant_Essential_Hypertension'),
('HTO:Monitoring_and_Follow-up', 'treats', 'HTO:Mild_Pre-Eclampsia'),
('HTO:Mortality_and_Serious_Complications', 'createsTheRiskOf', 'HTO:Eclampsia'),
('HTO:Mortality_and_Serious_Complications', 'createsTheRiskOf', 'HTO:Malignant_Renovascular_Hypertension'),
('HTO:Mortality_and_Serious_Complications', 'createsTheRiskOf', 'HTO:Malignant_Secondary_Hypertension'),
('HTO:Mortality_and_Serious_Complications', 'createsTheRiskOf', 'HTO:Persistent_Fetal_Circulation_Syndrome'),
('HTO:Mortality_and_Serious_Complications', 'createsTheRiskOf', 'HTO:Pulmonary_Venoocclusive_Disease'),
('HTO:Motor_Symptoms', 'isSymptomOf', 'HTO:Benign_Hypertensive_Renal_Disease'),
('HTO:Motor_Symptoms', 'isSymptomOf', 'HTO:Renovascular_Hypertension'),
('HTO:Nephrotrophic_Syndrome', 'createsTheRiskOf', 'HTO:Benign_Hypertensive_Renal_Disease'),
('HTO:Neurological_Factors', 'canCause', 'HTO:Eclampsia'),
('HTO:Neuropathic_Complications', 'createsTheRiskOf', 'HTO:Diabetes'),
('HTO:Obstetric_Care', 'treats', 'HTO:Eclampsia'),
('HTO:Obstetric_Care', 'treats', 'HTO:Mild_Pre-Eclampsia'),
('HTO:Obstetric_Care', 'treats', 'HTO:Severe_Pre-Eclampsia'),
('HTO:Occupational_Factors', 'canCause', 'HTO:Pulmonary_Venoocclusive_Disease'),
('HTO:Organ-specific_Complications', 'createsTheRiskOf', 'HTO:Mild_Pre-Eclampsia'),
('HTO:Organ-specific_Complications', 'createsTheRiskOf', 'HTO:Persistent_Fetal_Circulation_Syndrome'),
('HTO:Organ-specific_Complications', 'createsTheRiskOf', 'HTO:Severe_Pre-Eclampsia'),
('HTO:Pancreatic_Factors', 'canCause', 'HTO:Diabetes'),
('HTO:Perinatal_Factors', 'canCause', 'HTO:Persistent_Fetal_Circulation_Syndrome'),
('HTO:Pregnancy_Related_Factors', 'canCause', 'HTO:Eclampsia'),
('HTO:Pregnancy_Related_Factors', 'canCause', 'HTO:Mild_Pre-Eclampsia'),
('HTO:Pregnancy_Related_Factors', 'canCause', 'HTO:Severe_Pre-Eclampsia'),
('HTO:Pregnancy_and_Birth-related-complications', 'createsTheRiskOf', 'HTO:Eclampsia'),
('HTO:Pregnancy_and_Birth-related-complications', 'createsTheRiskOf', 'HTO:Mild_Pre-Eclampsia'),
('HTO:Pregnancy_and_Birth-related-complications', 'createsTheRiskOf', 'HTO:Severe_Pre-Eclampsia'),
('HTO:Proteinuria', 'createsTheRiskOf', 'HTO:Benign_Hypertensive_Renal_Disease'),
('HTO:Pulmonary_Complications', 'createsTheRiskOf', 'HTO:Malignant_Hypertensive_Renal_Disease'),
('HTO:Pulmonary_Complications', 'createsTheRiskOf', 'HTO:Pulmonary_Venoocclusive_Disease'),
('HTO:Renal_Care', 'treats', 'HTO:Benign_Renovascular_Hypertension'),
('HTO:Renal_Care', 'treats', 'HTO:Malignant_Renovascular_Hypertension'),
('HTO:Renal_Care', 'treats', 'HTO:Malignant_Secondary_Hypertension'),
('HTO:Renal_Care', 'treats', 'HTO:Nephrosclerosis'),
('HTO:Renal_Failure', 'createsTheRiskOf', 'HTO:Benign_Essential_Hypertension'),
('HTO:Renal_Failure', 'createsTheRiskOf', 'HTO:Benign_Hypertensive_Renal_Disease'),
('HTO:Renal_Failure', 'createsTheRiskOf', 'HTO:Malignant_Secondary_Hypertension'),
('HTO:Renal_Failure', 'createsTheRiskOf', 'HTO:Nephrosclerosis'),
('HTO:Renal_Failure', 'createsTheRiskOf', 'HTO:Renovascular_Hypertension'),
('HTO:Renal_Related_Factors', 'canCause', 'HTO:Eclampsia'),
('HTO:Respiratory_Factors', 'canCause', 'HTO:Benign_Secondary_Hypertension'),
('HTO:Respiratory_Support', 'treats', 'HTO:Persistent_Fetal_Circulation_Syndrome'),
('HTO:Respiratory_Symptoms', 'isSymptomOf', 'HTO:Benign_Essential_Hypertension'),
('HTO:Respiratory_Symptoms', 'isSymptomOf', 'HTO:Benign_Hypertensive_Renal_Disease'),
('HTO:Respiratory_Symptoms', 'isSymptomOf', 'HTO:Benign_Renovascular_Hypertension'),
('HTO:Respiratory_Symptoms', 'isSymptomOf', 'HTO:Benign_Secondary_Hypertension'),
('HTO:Respiratory_Symptoms', 'isSymptomOf', 'HTO:Malignant_Essential_Hypertension'),
('HTO:Respiratory_Symptoms', 'isSymptomOf', 'HTO:Malignant_Hypertensive_Renal_Disease'),
('HTO:Respiratory_Symptoms', 'isSymptomOf', 'HTO:Malignant_Secondary_Hypertension'),
('HTO:Respiratory_Symptoms', 'isSymptomOf', 'HTO:Persistent_Fetal_Circulation_Syndrome'),
('HTO:Respiratory_Symptoms', 'isSymptomOf', 'HTO:Pulmonary_Venoocclusive_Disease'),
('HTO:Respiratory_Symptoms', 'isSymptomOf', 'HTO:Severe_Pre-Eclampsia'),
('HTO:Retinal_Complications', 'createsTheRiskOf', 'HTO:Benign_Essential_Hypertension'),
('HTO:Retinal_Complications', 'createsTheRiskOf', 'HTO:Benign_Renovascular_Hypertension'),
('HTO:Retinal_Complications', 'createsTheRiskOf', 'HTO:Benign_Secondary_Hypertension'),
('HTO:Retinal_Complications', 'createsTheRiskOf', 'HTO:Diabetes'),
('HTO:Retinal_Complications', 'createsTheRiskOf', 'HTO:Malignant_Essential_Hypertension'),
('HTO:Retinal_Complications', 'createsTheRiskOf', 'HTO:Malignant_Secondary_Hypertension'),
('HTO:Retinal_Complications', 'createsTheRiskOf', 'HTO:Renovascular_Hypertension'),
('HTO:Sensory_Symptoms', 'isSymptomOf', 'HTO:Benign_Essential_Hypertension'),
('HTO:Sensory_Symptoms', 'isSymptomOf', 'HTO:Benign_Renovascular_Hypertension'),
('HTO:Sensory_Symptoms', 'isSymptomOf', 'HTO:Benign_Secondary_Hypertension'),
('HTO:Sensory_Symptoms', 'isSymptomOf', 'HTO:Pulmonary_Venoocclusive_Disease'),
('HTO:Sensory_Symptoms', 'isSymptomOf', 'HTO:Renovascular_Hypertension'),
('HTO:Surgical_Interventions', 'treats', 'HTO:Benign_Secondary_Hypertension'),
('HTO:Surgical_Interventions', 'treats', 'HTO:Pulmonary_Venoocclusive_Disease'),
('HTO:Surgical_Interventions', 'treats', 'HTO:Severe_Pre-Eclampsia'),
('HTO:Urinary_Changes', 'isSymptomOf', 'HTO:Benign_Hypertensive_Renal_Disease'),
('HTO:Urinary_Changes', 'isSymptomOf', 'HTO:Malignant_Hypertensive_Renal_Disease'),
('HTO:Urinary_Changes', 'isSymptomOf', 'HTO:Nephrosclerosis'),
('HTO:Urinary_Changes', 'isSymptomOf', 'HTO:Severe_Pre-Eclampsia'),
('HTO:Vascular_Factors', 'canCause', 'HTO:Benign_Renovascular_Hypertension'),
('HTO:Vascular_Factors', 'canCause', 'HTO:Benign_Secondary_Hypertension'),
('HTO:Vascular_Factors', 'canCause', 'HTO:Malignant_Renovascular_Hypertension'),
('HTO:Vascular_Factors', 'canCause', 'HTO:Malignant_Secondary_Hypertension'),
('HTO:Visual_Symptoms', 'isSymptomOf', 'HTO:Benign_Essential_Hypertension'),
('HTO:Visual_Symptoms', 'isSymptomOf', 'HTO:Benign_Renovascular_Hypertension'),
('HTO:Visual_Symptoms', 'isSymptomOf', 'HTO:Diabetes'),
('HTO:Visual_Symptoms', 'isSymptomOf', 'HTO:Eclampsia'),
('HTO:Visual_Symptoms', 'isSymptomOf', 'HTO:Malignant_Essential_Hypertension'),
('HTO:Visual_Symptoms', 'isSymptomOf', 'HTO:Malignant_Renovascular_Hypertension'),
('HTO:Visual_Symptoms', 'isSymptomOf', 'HTO:Malignant_Secondary_Hypertension'),
('HTO:Visual_Symptoms', 'isSymptomOf', 'HTO:Mild_Pre-Eclampsia'),
('HTO:Visual_Symptoms', 'isSymptomOf', 'HTO:Renovascular_Hypertension'),
('HTO:Visual_Symptoms', 'isSymptomOf', 'HTO:Severe_Pre-Eclampsia');

-- 조회 예시: 고혈압을 일으키는 원인 찾기 (역방향 탐색)
-- SELECT c.label_ko FROM hto_relations r JOIN hto_concepts c ON c.concept_id = r.from_concept
-- WHERE r.relation_type = 'canCause' AND r.to_concept = 'HTO:Essential_Hypertension';
--
-- 조회 예시: 특정 증상이 어떤 질환의 증상인지 찾기
-- SELECT c.label_ko FROM hto_relations r JOIN hto_concepts c ON c.concept_id = r.to_concept
-- WHERE r.relation_type = 'isSymptomOf' AND r.from_concept = 'HTO:Blood_Pressure-related_Symptoms';